# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FilmApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FilmApp

  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.4'
  pod 'UIImageColors'

  target 'FilmAppTests' do
    inherit! :search_paths
    # Pods for testing
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.4'
  pod 'UIImageColors'
  end

  target 'FilmAppUITests' do
    # Pods for testing
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.4'
  pod 'UIImageColors'
  end

end
